name: Education
description: "education user Application"
publish_to: 'none '
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.0
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  provider: 6.0.5
  states_rebuilder: ^6.2.0
  dot_navigation_bar: ^1.0.0
  flutter_svg: ^1.1.0
  badges: 2.0.2
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  cached_network_image: ^3.3.0
  flutter_animate: 4.1.1+1
  font_awesome_flutter: 10.6.0
  shared_preferences: ^2.2.2
  http: ^1.0.0
  fluttertoast: ^8.2.3
  lottie: ^2.7.0
  url_launcher: ^6.1.7
  webview_flutter: ^2.0.0
  motion_toast: ^2.6.4
  get: ^4.6.6
  get_storage: ^2.0.3
  flutter_credit_card: ^3.0.6
  awesome_card: ^1.1.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_cors: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  ribbon_widget: ^1.0.5
  getwidget: ^4.0.0
  flutter_super_html_viewer: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/icons/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/icons/logo.png"
      background_color: "#FFFFFF"
      theme_color: "#846046"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
